### ISSUE TITLE
react-clock has dependency on "@types/react": "*"

### ISSUE THREAD

**Issue by rcbevans** [wojtekmaj/react-clock#132]
Yarn is pulling in @types/react 18 into my react 17 project because of this transitive dependency which is causing type errors due to incompatible react definitions.

**Comment by wojtekmaj** [comment]
Not sure what can I do about that. You can certainly dedupe dependency yourself, but I understand this is suboptimal. Any other ideas how I can help out?

**Comment by rcbevans** [comment]
Just need to remove it from deps and make it a devDep, same as in react-time-picker.

I was able to explicitly make react-clock 4.0 a dependency and that worked around it for now.
