### ISSUE TITLE
Drag clock hands and set time? 

### ISSUE THREAD

**Issue by Tzikas** [wojtekmaj/react-clock#14]
Is there a way I can add a drag event to the hands of the clock and set the time that way?

**Comment by wojtekmaj** [comment]
Hi! That would be super neat, although not trivial to implement. Let's keep it in the backlog!

**Comment by johnreynoldsventure** [comment]
Should I be able to click on the hour/minutes to set the time?

**Comment by wojtekmaj** [comment]
No, at the moment React-Clock is presentational only.

**Comment by fivethreeo** [comment]
This would be great on mobile. Also there should be arrows on the fields for mobile.

**Comment by MakhouT** [comment]
Has this ever been implemented?
