### ISSUE TITLE
TS2589: Type instantiation is excessively deep and possibly infinite.

### ISSUE THREAD

**Issue by juanjalvarez** [wojtekmaj/react-clock#143]
I am getting this compilation error:

`TS2589: Type instantiation is excessively deep and possibly infinite.`

I attached a screenshot of a code snippet and these are my relevant dependencies:

"react": "18.2.0",
"react-clock": "^4.1.0",
"react-dom": "18.2.0",
"react-scripts": "5.0.1",
"typescript": "4.4.2",

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/8794965/221388627-a8419909-a89c-40ab-9b3e-769cd7b719c1.png">

<img width="545" alt="image" src="https://user-images.githubusercontent.com/8794965/221388636-fd532dd2-1456-4e3c-aefb-04c7b505655e.png">

**Comment by wojtekmaj** [comment]
Do you get the problem with the latest TypeScript version, too?

**Comment by wojtekmaj** [comment]
As this is only a problem with older TypeScript versions, the current behavior is helpful for users keeping their dependencies up to date, and it's going to be even less of a problem as more people update, I'll consider this a wontfix. However, a contribution adding special, limited functionality types to increase backwards compatibility is still welcome.
