### ISSUE TITLE
Error: require() of ES Module

### ISSUE THREAD

**Issue by deankemball** [wojtekmaj/react-clock#157]
I'm using [react-datetimerange-picker](https://github.com/wojtekmaj/react-datetimerange-picker) which has `react-clock` as  a sub-dependency. When I try to run my NextJs app I get the following error:

`
Error: require() of ES Module /Users/dean/dev/oyoun-project/node_modules/react-clock/node_modules/get-user-locale/dist/esm/index.js from /Users/dean/dev/oyoun-project/node_modules/react-clock/dist/cjs/shared/hourFormatter.js not supported.
Instead change the require of index.js in /Users/dean/dev/oyoun-project/node_modules/react-clock/dist/cjs/shared/hourFormatter.js to a dynamic import() which is available in all CommonJS modules.
`

I have in my `package.json` the `type: module`. I assume this is causing the error, which says I cannot use the `require` statement.

Have you encountered this before?

**Comment by anders-kaffia** [comment]
I have the same error. I am also using Next JS. I tried looking into the `transpilePackages` option for next config but that didn't help.

**Comment by wojtekmaj** [comment]
That's quite strange I must say, as react-clock ships CJS and ESM versions, CJS requiring - surprise - CJS, ESM - importing ESM. I have a suspicion #158 might fix that, or at least move the error a dependency "up", resolving the issue between react-clock and get-user-locale, but I'm not sure.

**Comment by wojtekmaj** [comment]
Mmmm, I think I got it. Working for me in Next.js.

You'll need to bump `get-user-locale` package to verify. For example, in Yarn:

`yarn up get-user-locale -R`

Alternatively, remove `react-clock` and add again.

**Comment by anders-kaffia** [comment]
Wow, that did the trick! I removed `react-clock`, ran `rm -rf node_modules`, and then added it back in. Thanks so much for the speedy help here @wojtekmaj !

**Comment by wojtekmaj** [comment]
Gosh CJS/ESM double packages are a pain :joy:

**Comment by deankemball** [comment]
> I have the same error. I am also using Next JS. I tried looking into the `transpilePackages` option for next config but that didn't help. I am just using `react-clock`. Next version: 13.2.3

Since creating the issue I found a fix for my situation. Firstly, I was using Next 12.x, so I upgraded to Next 13.2.3. This allowed me to use `transpilePackages`.

To get it working then, I added this block to my `next.config.mjs`: 

`transpilePackages: [
        "react-clock",
        "@wojtekmaj/react-datetimerange-picker",
        "get-user-locale",
    ],
    experimental: { esmExternals: "loose" },
    `

Since then it's working.
