### ISSUE TITLE
100% cpu

### ISSUE THREAD

**Issue by thisconnect** [wojtekmaj/react-clock#21]
I get really terrible performance when passing a `Date` as value.

Broser: Chrome 80
OS: macOS

It seems as that the datetime attribute updates on every frame, see screenshot.

![Screen Shot 2020-03-15 at 8 49 28 AM](https://user-images.githubusercontent.com/546900/76697660-fda99400-6699-11ea-98f5-bd9852523980.png)

Code

```jsx
import React, { useState } from 'react'
import Clock from 'react-clock'
// import './App.css'

function App() {
  const [time, setTime] = useState(new Date())

  setInterval(() => setTime(new Date()), 1000)

  return (
    <Clock
      value={time}
    />
  )
}

export default App
```

Edit: I'm testing in a create-react-app production build with `npx serve build`

**Comment by wojtekmaj** [comment]
The reason for this is because you're creating an infinite number of intervals (+1 per every render, first rerender happens after 1 second, 1 second later you have 2, then 4, then 8 rerenders per secoond...), because it's not wrapped in useEffect.

```diff
-  setInterval(() => setTime(new Date()), 1000)
+  useEffect(() => {
+    setInterval(() => setTime(new Date()), 1000)
+  }, [])
```
