### ISSUE TITLE
React clock not displaying

### ISSUE THREAD

**Issue by dardar4** [wojtekmaj/react-clock#30]
Hi,
I can't seem to make the clock render correctly.
I made a new react project using create-react-app and followed the example from the docs but nothing is rendered

see exmpale here: 
https://codesandbox.io/s/9vu0o?file=/src/App.js

is this package still supported?

**Comment by wojtekmaj** [comment]
You forgot the styles

https://github.com/wojtekmaj/react-clock#custom-styling
