### ISSUE TITLE
Support locales

### ISSUE THREAD

**Issue by mehdi-developer** [wojtekmaj/react-clock#31]
Please include a prop with numbersType to be in persian or english format like this :

```
numbersType={"persian" ||  "english"}

// In english -> 12345...
// In persian -> ۱۲۳۴۵...
```

Thanks in advance .

**Comment by wojtekmaj** [comment]
Note to self: Kinda similar to implement to https://github.com/wojtekmaj/react-calendar/commit/a77389f310bc16abdbe01c72ae03f491e01361b6
