### ISSUE TITLE
Color Customization

### ISSUE THREAD

**Issue by pedrozocatelli** [wojtekmaj/react-clock#8]
There is a way that I can customize the color of the pointers and hour/minutes marker?

**Comment by pedrozocatelli** [comment]
And the background too, so when It's like, past 6 pm, the background turns black/greyish.

**Comment by wojtekmaj** [comment]
Hi,
you can import React-Clock without the default styles and add your own ones.

https://github.com/wojtekmaj/react-clock#custom-styling

You may also just overwrite whatever you need to overwrite without removing default styling - depends on how much you'd get in conflict with them.

You can find the [source stylesheet](https://github.com/wojtekmaj/react-clock/blob/master/src/Clock.less) that you can base your work on in the repository.
